### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by astoff** [xuchunyang/DevDocs.el#4]
Are you still maintaining this package?

I wrote a new devdocs integration package (https://github.com/astoff/evdocs/), and when I submitted it to ELPA it was [suggest](https://lists.gnu.org/archive/html/emacs-devel/2021-05/msg01362.html) to check the possibility of merging the two packages.

If that sounds okay for you, I would then just add the `devdocs-search` command to my package and take over the namespace `devdocs`.

Please let me know what you think. Thanks!

**Comment by xuchunyang** [comment]
> Are you still maintaining this package?

Nope.


> If that sounds okay for you, I would then just add the `devdocs-search` command to my package and take over the namespace `devdocs`.

That's OK with me.

**Comment by astoff** [comment]
Great! The new version of the package will be on GNU ELPA and MELPA soon.

**Comment by astoff** [comment]
The new devdocs package is now on GNU ELPA and MELPA.
